name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch, e.g., 'master'

permissions:
  contents: write # To allow GitHub Actions to commit the built docs to gh-pages branch
  pages: write # To allow the deploy-pages action to deploy to GitHub Pages
  id-token: write # For OIDC authentication for pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest stable Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python pymdown-extensions

      - name: Build MkDocs site
        run: mkdocs build

      # --- CRUCIAL STEP FOR /docs/ BASE URL ---
      # This creates a temporary root directory, moves the built 'site' content
      # into its 'docs' subdirectory, and adds a .nojekyll file.
      # This structure matches what GitHub Pages expects when you want your documentation
      # served from 'https://aitzazimtiaz.github.io/arsla-lang/docs/'
      - name: Prepare site for /docs/ deployment
        run: |
          mkdir -p temp_deploy_root/docs # Create the target /docs/ folder
          mv ./site/* ./temp_deploy_root/docs/ # Move all built site content into temp_deploy_root/docs/
          # Create a .nojekyll file at the root to ensure GitHub Pages serves all content directly
          touch temp_deploy_root/.nojekyll
          echo "--- Final structure to be uploaded (temp_deploy_root): ---"
          ls -R ./temp_deploy_root/
          echo "--- Content of ./temp_deploy_root/docs/language-reference/builtins/index.html (first 20 lines) ---"
          head -n 20 ./temp_deploy_root/docs/language-reference/builtins/index.html || echo "File not found or empty in temp_deploy_root/docs."
      # --- END CRUCIAL STEP ---

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './temp_deploy_root' # Upload this new root directory as the artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
