name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for considering development for arsla, the project maintainer will look forward into this issue."
        pr-message: "Thank you for considering development for arsla, the project maintainer will look forward into this PR."
