name: Ruff Auto-Fix (Direct Commit)

on: push

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff and Auto-fix
        run: |
          set +e  # Don't exit on Ruff failure (if it can't fix everything)
          ruff check . --fix
          set -e

          git config --global user.name "dumbog"
          git config --global user.email "dumbog@example.com"

          git add .

          if ! git diff --cached --quiet; then
            git commit -m "fix: [auto-fix] lint issues by Ruff 🤖"
            git push origin HEAD
          else
            echo "No changes to commit."
          fi
