- name: Run Ruff and Auto-fix
  id: ruff_fix
  run: |
    set +e  # ignore errors so script continues
    ruff check . --fix
    set -e  # restore exit-on-error

    git config --global user.name "dumbog"
    git config --global user.email "dumbog@example.com"

    BRANCH_NAME="auto/lint-fix-${{ github.run_id }}"
    git checkout -b "$BRANCH_NAME"

    git add .
    if ! git diff --cached --quiet; then
      git commit -m "fix: [auto-fix] lint issues by Ruff 🤖"
      git push https://x-access-token:${{ secrets.DUMBOG_PAT }}@github.com/${{ github.repository }} "$BRANCH_NAME"
      echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
      echo "changes_made=true" >> $GITHUB_OUTPUT
    else
      echo "changes_made=false" >> $GITHUB_OUTPUT
