name: Ruff Auto-Fix Direct Commit

on:
  push:
    paths:
      - '**/*.py'

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff and Auto-fix, commit if needed
        env:
          GITHUB_TOKEN: ${{ secrets.DUMBOG_PAT }}
        run: |
          git config --global user.name "dumbog"
          git config --global user.email "dumbog@example.com"

          ruff check . --fix

          git add .
          if ! git diff --cached --quiet; then
            git commit -m "fix: [auto-fix] lint issues by Ruff 🤖"
            git push
          else
            echo "No lint fixes needed."
          fi
